spring:
  cloud:
    config:   #云配置
      uri: http://192.168.145.137:8888  #spring cloud config云配置服务端口
      name: itoken-eureka   # 服务名称
      label: master  #git仓库版本
      profile: prod  #配置文件类型，dev,test,prod